using System.Globalization;
using EverydaySlideshow.Core;
using EverydaySlideshow.Infrastructure;

namespace EverydaySlideshow.Services;

public sealed class LocalizedText : ObservableObject
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["AppTitle"] = "EverydaySlideshow",
        ["MenuFile"] = "File",
        ["MenuPlay"] = "Play",
        ["MenuMood"] = "Mood",
        ["MenuView"] = "View",
        ["MenuSettings"] = "Settings",
        ["MenuLanguage"] = "Language",
        ["MenuHelp"] = "Help",
        ["CheckForUpdates"] = "Check for updates...",
        ["LanguageEnglish"] = "English",
        ["LanguageJapanese"] = "Japanese",
        ["AddFolder"] = "Add folder",
        ["ReloadAll"] = "Reload all",
        ["CreatePlaylist"] = "Create playlist",
        ["MoveDeleteCandidatesToRecycleBin"] = "Move delete candidates to Recycle Bin",
        ["ResetHidden"] = "Reset hidden items",
        ["ResetDeleteCandidates"] = "Reset delete candidates",
        ["Exit"] = "Exit",
        ["PlayAll"] = "Shuffle all",
        ["ResumePrevious"] = "Resume previous",
        ["FavoritesOnly"] = "Favorites only",
        ["WatchLater"] = "Watch later",
        ["RecentlyUnseen"] = "Not seen recently",
        ["AnniversaryAroundToday"] = "Around this date last year",
        ["RegisteredFolders"] = "Registered folders",
        ["FolderCountPrefix"] = "Folders",
        ["FolderCountSuffix"] = "",
        ["Playlists"] = "Playlists",
        ["MoodDefault"] = "Default",
        ["MoodWork"] = "Work",
        ["MoodBedtime"] = "Bedtime",
        ["MoodSafe"] = "Safe mode",
        ["CreateCustom"] = "Create custom",
        ["Custom"] = "Custom",
        ["WindowMode"] = "Window",
        ["Fullscreen"] = "Fullscreen",
        ["BorderlessWindow"] = "Borderless",
        ["StartFullscreen"] = "Start slideshows fullscreen",
        ["Topmost"] = "Always on top",
        ["DarkMode"] = "Dark mode",
        ["FitMode"] = "Display mode",
        ["Monitor"] = "Display monitor",
        ["SmartShuffle"] = "Smart shuffle",
        ["Loop"] = "Loop",
        ["PauseEachPhoto"] = "Pause each photo",
        ["IncludeVideos"] = "Include videos",
        ["MuteVideo"] = "Mute videos",
        ["IdleAutoPlaySetting"] = "Auto-play when this screen is idle",
        ["AutoStartWindows"] = "Start with Windows",
        ["NoFoldersHint"] = "No folders yet. Start with Add folder on the left.",
        ["SubfoldersLabel"] = "Subfolders: ",
        ["PrivateLabel"] = "  Private: ",
        ["Play"] = "Play",
        ["Delete"] = "Delete",
        ["PlaylistHelp"] = "Combine any registered folders and play them together.",
        ["Playback"] = "Playback",
        ["DisplayAndWindow"] = "View & Window",
        ["WaitTime"] = "Wait",
        ["Minutes"] = "min",
        ["Brightness"] = "Brightness",
        ["Speed"] = "Speed",
        ["CustomSeconds"] = "Custom seconds",
        ["CurrentSecondsFormat"] = "Current: {0}s",
        ["Organization"] = "Organize",
        ["DeleteCandidate"] = "Delete candidate",
        ["First"] = "First",
        ["Home"] = "Home",
        ["Fit"] = "Fit",
        ["Fill"] = "Fill",
        ["Original"] = "Original",
        ["BlurBackground"] = "Blur background",
        ["NoPreference"] = "No preference",
        ["MorePortraits"] = "More portraits",
        ["FewerPortraits"] = "Fewer portraits",
        ["SecondsOption"] = "{0}s",
        ["MinutesOption"] = "{0} min",
        ["Pause"] = "Pause",
        ["Resume"] = "Resume",
        ["Hide"] = "Hide",
        ["Unhide"] = "Unhide",
        ["UnwatchLater"] = "Remove watch later",
        ["RemoveDeleteCandidate"] = "Remove candidate",
        ["MediaVideo"] = "Video",
        ["MediaPhoto"] = "Photo",
        ["PrimaryMonitor"] = "Primary",
        ["SecondaryMonitor"] = "Secondary",
        ["FolderBrowserDescription"] = "Choose a folder that contains photos or videos.",
        ["StatusNoFolders"] = "Add a folder to start a slideshow right away.",
        ["StatusWakeResume"] = "Resumed after wake.",
        ["StatusFolderAdded"] = "Added \"{0}\".",
        ["ConfirmDeleteFolderTitle"] = "Remove registered folder",
        ["ConfirmDeleteFolderMessage"] = "Remove \"{0}\" from registered folders? The photo files themselves will not be deleted.",
        ["StatusFolderRemoved"] = "Removed \"{0}\" from registered folders.",
        ["StatusFoldersLoaded"] = "Loaded {0:N0} registered folders.",
        ["StatusFoldersAndPlaylistsLoaded"] = "Loaded {0:N0} registered folders and {1:N0} playlists.",
        ["StatusAddFolderFirst"] = "Add a photo folder first.",
        ["ScanLoading"] = "Loading \"{0}\"...",
        ["ScanCount"] = "\"{0}\": {1:N0} items",
        ["ScanSaved"] = "\"{0}\": saved {1:N0} items.",
        ["ScanCancelled"] = "Loading was canceled.",
        ["StatusPlaylistNeedsFolder"] = "Add folders before creating a playlist.",
        ["DefaultPlaylistName"] = "New playlist",
        ["StatusPlaylistCreated"] = "Created playlist \"{0}\".",
        ["ConfirmDeletePlaylistTitle"] = "Delete playlist",
        ["ConfirmDeletePlaylistMessage"] = "Delete \"{0}\"? Registered folders and photo files will not be deleted.",
        ["StatusPlaylistDeleted"] = "Deleted playlist \"{0}\".",
        ["StatusStartAddFolderFirst"] = "Add a photo folder first.",
        ["StatusNoPlayableMedia"] = "No playable photos or videos were found. Check filters or folder settings.",
        ["MoodWorkSelected"] = "Work mode selected. Start the slideshow with a play button.",
        ["MoodBedtimeSelected"] = "Bedtime mode selected. Start the slideshow with a play button.",
        ["MoodSafeSelected"] = "Safe mode selected. Start the slideshow with a play button.",
        ["MoodDefaultSelected"] = "Default mode selected. Start the slideshow with a play button.",
        ["CustomMoodDraftNameFormat"] = "Custom {0}",
        ["CustomMoodFallbackName"] = "Custom",
        ["StatusCustomMoodCreated"] = "Created mood mode \"{0}\".",
        ["StatusCustomMoodSelected"] = "Selected mood mode \"{0}\". Start the slideshow with a play button.",
        ["StatusCustomMoodDeleted"] = "Deleted mood mode \"{0}\".",
        ["StatusReachedEnd"] = "Reached the end.",
        ["StatusSkippedUnreadable"] = "Skipped an unreadable file: {0}",
        ["IdleAutoPlayTitle"] = "Auto-play when this screen is idle",
        ["StatusHidden"] = "Hidden this photo.",
        ["StatusUnhidden"] = "Unhidden this photo.",
        ["StatusDeleteCandidateAdded"] = "Added to delete candidates.",
        ["StatusDeleteCandidateRemoved"] = "Removed from delete candidates.",
        ["StatusWatchLaterAdded"] = "Added to Watch later.",
        ["StatusWatchLaterRemoved"] = "Removed from Watch later.",
        ["StatusNoDeleteCandidates"] = "There are no delete candidates.",
        ["ConfirmPurgeDeleteTitle"] = "Delete candidates for real",
        ["ConfirmPurgeDeleteMessage"] = "Move {0:N0} items to the Windows Recycle Bin?",
        ["StatusMovedToRecycleBin"] = "Moved {0:N0} items to the Recycle Bin.",
        ["ConfirmResetHiddenTitle"] = "Reset hidden items",
        ["ConfirmResetHiddenMessage"] = "Return all hidden photos and videos to the visible set?",
        ["StatusResetHidden"] = "Reset {0:N0} hidden items.",
        ["ConfirmResetDeleteTitle"] = "Reset delete candidates",
        ["ConfirmResetDeleteMessage"] = "Return all delete candidates to normal? Files will not be deleted.",
        ["StatusResetDelete"] = "Reset {0:N0} delete candidates.",
        ["StatusCheckingUpdates"] = "Checking GitHub Releases for updates...",
        ["StatusUpdateAvailable"] = "Version {0} is available. Opening GitHub Releases...",
        ["StatusUpToDate"] = "You are using the latest version ({0}).",
        ["StatusUpdateNotConfigured"] = "Update checks are not configured for this build.",
        ["StatusNoReleaseFound"] = "No GitHub Release was found for this app yet.",
        ["StatusUpdateNetworkError"] = "Could not check for updates. Check your connection and try again.",
        ["StatusUpdateInvalidResponse"] = "GitHub returned an update response this app could not read.",
        ["FolderDialogTitle"] = "Register folder",
        ["DisplayName"] = "Display name",
        ["Location"] = "Location",
        ["IncludeSubfoldersDialog"] = "Include subfolders",
        ["AvoidInSafeMode"] = "Avoid in safe mode",
        ["Register"] = "Register",
        ["Cancel"] = "Cancel",
        ["PlaylistDialogTitle"] = "Create playlist",
        ["PlaylistDialogDefaultName"] = "Favorite mix",
        ["Create"] = "Create",
        ["ChooseOneFolder"] = "Choose at least one folder.",
        ["Name"] = "Name",
        ["IncludedFolders"] = "Folders to include",
        ["CustomMoodDialogTitle"] = "Custom mood mode",
        ["MuteVideoDialog"] = "Mute video audio",
        ["Save"] = "Save",
        ["SecondsNumericMessage"] = "Enter the seconds as a number.",
        ["BrightnessNumericMessage"] = "Enter brightness as a number from 0.35 to 1.00.",
        ["SwitchSeconds"] = "Slide seconds",
        ["PortraitPhotos"] = "Portrait photos"
    };

    private static readonly IReadOnlyDictionary<string, string> Japanese = new Dictionary<string, string>
    {
        ["AppTitle"] = "EverydaySlideshow",
        ["MenuFile"] = "ファイル",
        ["MenuPlay"] = "再生",
        ["MenuMood"] = "気分モード",
        ["MenuView"] = "表示",
        ["MenuSettings"] = "設定",
        ["MenuLanguage"] = "言語",
        ["MenuHelp"] = "ヘルプ",
        ["CheckForUpdates"] = "更新を確認...",
        ["LanguageEnglish"] = "English",
        ["LanguageJapanese"] = "日本語",
        ["AddFolder"] = "フォルダを追加",
        ["ReloadAll"] = "すべて再読み込み",
        ["CreatePlaylist"] = "プレイリストを作成",
        ["MoveDeleteCandidatesToRecycleBin"] = "削除候補をごみ箱へ",
        ["ResetHidden"] = "非表示をすべて解除",
        ["ResetDeleteCandidates"] = "削除候補をすべて解除",
        ["Exit"] = "終了",
        ["PlayAll"] = "全部混ぜる",
        ["ResumePrevious"] = "前回の続きから",
        ["FavoritesOnly"] = "お気に入りだけ",
        ["WatchLater"] = "あとで見る",
        ["RecentlyUnseen"] = "最近見ていない写真",
        ["AnniversaryAroundToday"] = "去年の今日あたり",
        ["RegisteredFolders"] = "登録済みフォルダ",
        ["FolderCountPrefix"] = "フォルダ",
        ["FolderCountSuffix"] = "個",
        ["Playlists"] = "プレイリスト",
        ["MoodDefault"] = "デフォルト",
        ["MoodWork"] = "仕事中",
        ["MoodBedtime"] = "寝る前",
        ["MoodSafe"] = "安全モード",
        ["CreateCustom"] = "カスタムを作成",
        ["Custom"] = "カスタム",
        ["WindowMode"] = "通常ウィンドウ",
        ["Fullscreen"] = "フルスクリーン",
        ["BorderlessWindow"] = "枠なし",
        ["StartFullscreen"] = "全画面モードで開始",
        ["Topmost"] = "常に最前面",
        ["DarkMode"] = "ダークモード",
        ["FitMode"] = "表示方法",
        ["Monitor"] = "表示先モニター",
        ["SmartShuffle"] = "スマートシャッフル",
        ["Loop"] = "ループ",
        ["PauseEachPhoto"] = "写真ごとに一時停止",
        ["IncludeVideos"] = "動画を含める",
        ["MuteVideo"] = "動画を音なし",
        ["IdleAutoPlaySetting"] = "この画面のアイドル時の自動再生",
        ["AutoStartWindows"] = "Windows 起動時に自動起動",
        ["NoFoldersHint"] = "まだフォルダがありません。左の「フォルダを追加」から始めてください。",
        ["SubfoldersLabel"] = "サブフォルダ: ",
        ["PrivateLabel"] = "  個人用: ",
        ["Play"] = "再生",
        ["Delete"] = "削除",
        ["PlaylistHelp"] = "任意の登録フォルダを組み合わせて再生できます。",
        ["Playback"] = "再生",
        ["DisplayAndWindow"] = "表示と Window",
        ["WaitTime"] = "待ち時間",
        ["Minutes"] = "分",
        ["Brightness"] = "明るさ",
        ["Speed"] = "速度",
        ["CustomSeconds"] = "カスタム秒",
        ["CurrentSecondsFormat"] = "現在: {0}秒",
        ["Organization"] = "整理",
        ["DeleteCandidate"] = "削除候補",
        ["First"] = "最初へ",
        ["Home"] = "ホーム",
        ["Fit"] = "フィット",
        ["Fill"] = "フィル",
        ["Original"] = "原寸",
        ["BlurBackground"] = "背景ぼかし",
        ["NoPreference"] = "指定なし",
        ["MorePortraits"] = "縦写真多め",
        ["FewerPortraits"] = "縦写真少なめ",
        ["SecondsOption"] = "{0}秒",
        ["MinutesOption"] = "{0}分",
        ["Pause"] = "一時停止",
        ["Resume"] = "再開",
        ["Hide"] = "非表示",
        ["Unhide"] = "非表示解除",
        ["UnwatchLater"] = "あとで見る解除",
        ["RemoveDeleteCandidate"] = "候補解除",
        ["MediaVideo"] = "動画",
        ["MediaPhoto"] = "写真",
        ["PrimaryMonitor"] = "メイン",
        ["SecondaryMonitor"] = "サブ",
        ["FolderBrowserDescription"] = "写真や動画が入っているフォルダを選んでください。",
        ["StatusNoFolders"] = "フォルダを追加すると、すぐにスライドショーを始められます。",
        ["StatusWakeResume"] = "スリープ復帰後に再開しました。",
        ["StatusFolderAdded"] = "「{0}」を登録しました。",
        ["ConfirmDeleteFolderTitle"] = "登録フォルダを削除",
        ["ConfirmDeleteFolderMessage"] = "「{0}」を登録から削除します。写真ファイル自体は削除しません。よろしいですか？",
        ["StatusFolderRemoved"] = "「{0}」の登録を削除しました。",
        ["StatusFoldersLoaded"] = "登録済みフォルダ {0:N0} 件を読み込みました。",
        ["StatusFoldersAndPlaylistsLoaded"] = "登録済みフォルダ {0:N0} 件、プレイリスト {1:N0} 件を読み込みました。",
        ["StatusAddFolderFirst"] = "先に写真フォルダを追加してください。",
        ["ScanLoading"] = "「{0}」を読み込んでいます...",
        ["ScanCount"] = "「{0}」: {1:N0} 件",
        ["ScanSaved"] = "「{0}」: {1:N0} 件を保存しました。",
        ["ScanCancelled"] = "読み込みを中断しました。",
        ["StatusPlaylistNeedsFolder"] = "プレイリストを作るには、先にフォルダを追加してください。",
        ["DefaultPlaylistName"] = "新しいプレイリスト",
        ["StatusPlaylistCreated"] = "プレイリスト「{0}」を作成しました。",
        ["ConfirmDeletePlaylistTitle"] = "プレイリストを削除",
        ["ConfirmDeletePlaylistMessage"] = "「{0}」を削除します。登録フォルダや写真ファイルは削除しません。",
        ["StatusPlaylistDeleted"] = "プレイリスト「{0}」を削除しました。",
        ["StatusStartAddFolderFirst"] = "最初に写真フォルダを追加してください。",
        ["StatusNoPlayableMedia"] = "表示できる写真や動画が見つかりませんでした。フィルタやフォルダ設定を確認してください。",
        ["MoodWorkSelected"] = "仕事中モードを選びました。再生ボタンからスライドショーを始められます。",
        ["MoodBedtimeSelected"] = "寝る前モードを選びました。再生ボタンからスライドショーを始められます。",
        ["MoodSafeSelected"] = "安全モードを選びました。再生ボタンからスライドショーを始められます。",
        ["MoodDefaultSelected"] = "デフォルトモードを選びました。再生ボタンからスライドショーを始められます。",
        ["CustomMoodDraftNameFormat"] = "カスタム {0}",
        ["CustomMoodFallbackName"] = "カスタム",
        ["StatusCustomMoodCreated"] = "気分モード「{0}」を作成しました。",
        ["StatusCustomMoodSelected"] = "気分モード「{0}」を選びました。再生ボタンからスライドショーを始められます。",
        ["StatusCustomMoodDeleted"] = "気分モード「{0}」を削除しました。",
        ["StatusReachedEnd"] = "最後まで再生しました。",
        ["StatusSkippedUnreadable"] = "読み込めないファイルをスキップしました: {0}",
        ["IdleAutoPlayTitle"] = "この画面のアイドル時の自動再生",
        ["StatusHidden"] = "この写真を非表示にしました。",
        ["StatusUnhidden"] = "非表示を解除しました。",
        ["StatusDeleteCandidateAdded"] = "削除候補に入れました。",
        ["StatusDeleteCandidateRemoved"] = "削除候補を解除しました。",
        ["StatusWatchLaterAdded"] = "あとで見るに入れました。",
        ["StatusWatchLaterRemoved"] = "あとで見るを解除しました。",
        ["StatusNoDeleteCandidates"] = "削除候補はありません。",
        ["ConfirmPurgeDeleteTitle"] = "削除候補を実削除",
        ["ConfirmPurgeDeleteMessage"] = "{0:N0} 件を Windows のごみ箱へ移動します。よろしいですか？",
        ["StatusMovedToRecycleBin"] = "{0:N0} 件をごみ箱へ移動しました。",
        ["ConfirmResetHiddenTitle"] = "非表示をすべて解除",
        ["ConfirmResetHiddenMessage"] = "非表示にした写真や動画をすべて表示対象へ戻します。よろしいですか？",
        ["StatusResetHidden"] = "{0:N0} 件の非表示を解除しました。",
        ["ConfirmResetDeleteTitle"] = "削除候補をすべて解除",
        ["ConfirmResetDeleteMessage"] = "削除候補にした写真や動画をすべて通常状態へ戻します。ファイルは削除されません。よろしいですか？",
        ["StatusResetDelete"] = "{0:N0} 件の削除候補を解除しました。",
        ["StatusCheckingUpdates"] = "GitHub Releases で更新を確認しています...",
        ["StatusUpdateAvailable"] = "バージョン {0} が利用できます。GitHub Releases を開きます...",
        ["StatusUpToDate"] = "最新バージョンです ({0})。",
        ["StatusUpdateNotConfigured"] = "このビルドでは更新確認のリポジトリが未設定です。",
        ["StatusNoReleaseFound"] = "このアプリの GitHub Release はまだ見つかりませんでした。",
        ["StatusUpdateNetworkError"] = "更新を確認できませんでした。接続を確認してもう一度お試しください。",
        ["StatusUpdateInvalidResponse"] = "GitHub からの更新情報を読み取れませんでした。",
        ["FolderDialogTitle"] = "フォルダを登録",
        ["DisplayName"] = "表示名",
        ["Location"] = "場所",
        ["IncludeSubfoldersDialog"] = "サブフォルダも含める",
        ["AvoidInSafeMode"] = "安全モードでは避ける",
        ["Register"] = "登録",
        ["Cancel"] = "キャンセル",
        ["PlaylistDialogTitle"] = "プレイリストを作成",
        ["PlaylistDialogDefaultName"] = "お気に入りの組み合わせ",
        ["Create"] = "作成",
        ["ChooseOneFolder"] = "フォルダを1つ以上選んでください。",
        ["Name"] = "名前",
        ["IncludedFolders"] = "含めるフォルダ",
        ["CustomMoodDialogTitle"] = "カスタム気分モード",
        ["MuteVideoDialog"] = "動画の音を出さない",
        ["Save"] = "保存",
        ["SecondsNumericMessage"] = "秒数は数字で入力してください。",
        ["BrightnessNumericMessage"] = "明るさは 0.35 から 1.00 の数字で入力してください。",
        ["SwitchSeconds"] = "切り替え秒数",
        ["PortraitPhotos"] = "縦写真"
    };

    private AppLanguage _language = AppLanguage.English;

    public static AppLanguage CurrentLanguage { get; private set; } = AppLanguage.English;

    public AppLanguage Language => _language;

    public string this[string key]
    {
        get => Translate(_language, key);
        set { }
    }

    public void Use(AppLanguage language)
    {
        if (_language == language)
        {
            CurrentLanguage = language;
            return;
        }

        _language = language;
        CurrentLanguage = language;
        OnPropertyChanged(nameof(Language));
        OnPropertyChanged("Item[]");
    }

    public static string Translate(AppLanguage language, string key)
    {
        var table = language == AppLanguage.Japanese ? Japanese : English;
        if (table.TryGetValue(key, out var value))
        {
            return value;
        }

        return English.TryGetValue(key, out var fallback) ? fallback : key;
    }

    public static string Format(AppLanguage language, string key, params object?[] args)
        => string.Format(CultureInfo.CurrentCulture, Translate(language, key), args);
}
